# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This WORKSPACE verifies that the google-cloud-cpp-spanner libraries can be
# loaded into a different Bazel project.
workspace(name = "com_github_googleapis_google_cloud_cpp_spanner_test_install")

# Spanner currently does not have a release. Applications should use something
# like the following:
#
# http_archive(
#     name = "com_github_googleapis_google_cloud_cpp_spanner",
#     url = "http://github.com/googleapis/google-cloud-cpp-spanner/archive/v0.1.0.tar.gz",
#     strip_prefix = "google-cloud-cpp-spanner-0.1.0",
#     sha256 = "...",
# )
#

# But we want to test that the *current* version is correct, the CI builds
# always have the source in /v.
local_repository(
    name = "com_github_googleapis_google_cloud_cpp_spanner",
    path = "/v",
)

load("@com_github_googleapis_google_cloud_cpp_spanner//bazel:google_cloud_cpp_spanner_deps.bzl", "google_cloud_cpp_spanner_deps")

google_cloud_cpp_spanner_deps()

# Configure @com_google_googleapis to only compile C++ and gRPC:
load("@com_google_googleapis//:repository_rules.bzl", "switched_rules_by_language")

switched_rules_by_language(
    name = "com_google_googleapis_imports",
    cc = True,  # C++ support is only "Partially implemented", roll our own.
    grpc = True,
)

load("@com_github_googleapis_google_cloud_cpp_common//bazel:google_cloud_cpp_common_deps.bzl", "google_cloud_cpp_common_deps")

google_cloud_cpp_common_deps()

# Have to manually call the corresponding function for gRPC:
#   https://github.com/bazelbuild/bazel/issues/1550
load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")

grpc_deps()

load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")

grpc_extra_deps()
