#!/usr/bin/env bash
#
# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eu

readonly BINDIR=$(dirname "$0")

cat <<_EOF_
# Google Cloud Spanner C++ Client Library

<!-- This file is automatically generated by ci/test-markdown/$(basename "$0") -->

_EOF_

cat <<'_EOF_'
[![CI status docker/clang-tidy][docker/clang-tidy-shield]][docker/clang-tidy-link]
[![CI status docker/cmake][docker/cmake-shield]][docker/cmake-link]
[![CI status macos/bazel][macos/bazel-shield]][macos/bazel-link]
[![CI status windows/bazel][windows/bazel-shield]][windows/bazel-link]
[![Code Coverage Status][codecov-io-badge]][codecov-io-link]

[docker/clang-tidy-link]: https://storage.googleapis.com/cloud-cpp-kokoro-status/spanner/docker/clang-tidy-link.html
[docker/clang-tidy-shield]: https://storage.googleapis.com/cloud-cpp-kokoro-status/spanner/docker/clang-tidy.svg
[docker/cmake-link]: https://storage.googleapis.com/cloud-cpp-kokoro-status/spanner/docker/cmake-link.html
[docker/cmake-shield]: https://storage.googleapis.com/cloud-cpp-kokoro-status/spanner/docker/cmake.svg
[macos/bazel-link]: https://storage.googleapis.com/cloud-cpp-kokoro-status/spanner/macos/bazel-link.html
[macos/bazel-shield]: https://storage.googleapis.com/cloud-cpp-kokoro-status/spanner/macos/bazel.svg
[windows/bazel-shield]: https://storage.googleapis.com/cloud-cpp-kokoro-status/spanner-windows-bazel.svg
[windows/bazel-link]:   https://storage.googleapis.com/cloud-cpp-kokoro-status/spanner-windows-bazel-link.html
[codecov-io-badge]: https://codecov.io/gh/googleapis/google-cloud-cpp-spanner/branch/master/graph/badge.svg
[codecov-io-link]: https://codecov.io/gh/googleapis/google-cloud-cpp-spanner

> **NOTICE:** This repo will be merging with the
[googleapis/google-cloud-cpp](https://github.com/googleapis/google-cloud-cpp)
monorepo in 60 days, around **June 1, 2020**. This change should not break any
users who are using a released version. We expect this new monorepo
organization to be better for our existing and new customers going forward.
Please see
[googleapis/google-cloud-cpp#3612](https://github.com/googleapis/google-cloud-cpp/issues/3612)
for more details.

This repository contains an idiomatic C++ client library for interacting with
[Google Cloud Spanner](https://cloud.google.com/spanner/), which is a fully
managed, scalable, relational database service for regional and global
application data.

Please note that the Google Cloud C++ client libraries do **not** follow
[Semantic Versioning](http://semver.org/).

## Supported Platforms

* Windows, macOS, Linux
* C++11 (and higher) compilers (we test with GCC \>= 4.9, Clang >= 3.8, and MSVC \>= 2019)
* Environments with or without exceptions
* Bazel and CMake builds

## Documentation

* Official documentation about the [Cloud Spanner][cloud-spanner-docs] service
* [Reference doxygen documentation][doxygen-link] for each release of this client library
* Detailed header comments in our [public `.h`][source-link] files

[doxygen-link]: https://googleapis.dev/cpp/google-cloud-spanner/latest/
[cloud-spanner-docs]: https://cloud.google.com/spanner/docs/
[source-link]: https://github.com/googleapis/google-cloud-cpp-spanner/tree/master/google/cloud/spanner

## Quickstart

The [google/cloud/spanner/quickstart/][quickstart-link] directory contains a
minimal environment to help you quickly get started using this client library.
The following is the "Hello World" program you'll be running, which should give
you a taste of this library.

[quickstart-link]: https://github.com/googleapis/google-cloud-cpp-spanner/tree/master/google/cloud/spanner/quickstart

```cc
_EOF_

# Dumps the contents of quickstart.cc starting at the first #include, so we
# skip the license header comment.
sed -n '/^#/,$p' "${BINDIR}/../../google/cloud/spanner/quickstart/quickstart.cc"

cat <<'_EOF_'
````

## Contributing changes

See [`CONTRIBUTING.md`](CONTRIBUTING.md) for details on how to contribute to
this project, including how to build and test your changes as well as how to
properly format your code.

## Other Google Cloud C++ Libraries

* [Google Cloud Storage][gcs-link]
* [Google Cloud Bigtable][bigtable-link]

[gcs-link]: https://github.com/googleapis/google-cloud-cpp
[bigtable-link]: https://github.com/googleapis/google-cloud-cpp

## Licensing

Apache 2.0; see [`LICENSE`](LICENSE) for details.

_EOF_
